spring.application.name=api

# Conexión a la base de datos (PostgreSQL)
spring.datasource.url=${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# Configuración de JPA/Hibernate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.spatial=true
logging.level.org.springframework.jdbc=${LOG_LEVEL:INFO}

# Configuración del servidor
server.port=8080
spring.security.user.name=${API_USER:admin}
spring.security.user.password=${API_PASSWORD}