CREATE TABLE IF NOT EXISTS users (
    "id" BIGSERIAL PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password" VARCHAR(255) NOT NULL,
    "role" VARCHAR(50) NOT NULL CHECK ("role" IN ('DRIVER', 'OWNER')), -- Comillas aquí
    "terms_accepted" BOOLEAN NOT NULL DEFAULT FALSE,
    "state" BOOLEAN NOT NULL DEFAULT TRUE
);